name: Full Stack CI/CD

on:
  push:
    paths:
      - 'Project/react_frontend/**'
      - 'Project/spring_backend/**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Backend Dependencies and Run Server
        run: |
          ./gradlew bootRun & sleep 20
        working-directory: Project/spring_backend
       
      - name: Install Frontend Dependencies
        run: yarn install
        working-directory: Project/react_frontend

      - name: Frontend Build
        run: yarn build
        working-directory: Project/react_frontend

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          config-file: cypress.config.ts
          working-directory: Project/react_frontend
          start: yarn start
          wait-on: 'http://localhost:3000'  # Update this line
          wait-on-timeout: 120