name: Full Stack CI/CD

on:
  push:
    paths:
      - 'Project/react_frontend/**'
      - 'Project/spring_backend/**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Backend Dependencies and Run Server
        run: |
          ./gradlew bootRun & sleep 20
        working-directory: Project/spring_backend
       
      - name: Install Frontend Dependencies
        run: npm install
        working-directory: Project/react_frontend

      - name: Frontend Build
        run: yarn build
        working-directory: Project/react_frontend

      - name: Start Frontend
        run: yarn start
        working-directory: Project/react_frontend

      - name: Run Cypress tests
        run: npx cypress run --spec '**/spec.cy.ts'
        working-directory: Project/react_frontend
