name: Spring Backend CI/CD

on:
  push:
    paths:
      - 'Project/spring_backend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run unit tests
        run: ./gradlew test
        working-directory: Project/spring_backend
